[tools]
java = "21"
android-sdk = "latest"
node = "20"

[tasks.build]
description = "Build all targets"
run = "./gradlew build"

[tasks.compile-wasm]
description = "Compile Kotlin for WasmJs target"
run = "./gradlew compileKotlinWasmJs"

[tasks.run-demo]
description = "Run the WasmJs interactive browser REPL demo"
run = "./gradlew :demo-web:wasmJsBrowserDevelopmentRun"

[tasks.run-jvm]
description = "Run the JVM Desktop interactive shell REPL demo"
run = "./gradlew :demo-jvm:run"
